In [1]:
import pathlib
import pickle

import numpy as np
import scipy.sparse
import scipy.io
import pandas as pd

In [2]:
num_drug = 1482
num_dis = 793
# 5%为强负样本
hardnegatives=int(num_dis*0.05)
hardnegatives

39

In [4]:
us=np.load("USAM.npy")
dd=np.load("DDAM.npy")
score=np.load("SCORE_DD.npy")

In [5]:
sc=pd.DataFrame(score.T)
sc

0       1     2       3       4       5     6       7       8     \
0    0.0000  0.0013   0.0  0.0000  0.0000  0.0020   0.0  0.0000  0.0020   
1    0.0068  0.0000   0.0  0.0110  0.0000  0.0099   1.0  0.0204  0.0099   
2    0.0068  0.0000   0.0  0.0110  0.0000  0.0099   1.0  0.0204  0.0099   
3    0.0018  0.0008   0.0  0.0000  0.0395  0.0095   0.0  0.0263  0.0095   
4    0.0000  0.0000   0.0  0.0065  0.0000  0.0068   0.0  0.0000  0.0068   
..      ...     ...   ...     ...     ...     ...   ...     ...     ...   
788  0.0011  0.0005   0.0  0.0000  0.0000  0.0132   0.0  0.0167  0.0132   
789  0.0014  0.0000   0.0  0.0016  0.0000  0.0122   0.0  0.0000  0.0122   
790  0.0011  0.0000   0.0  0.0013  0.0000  0.0046   0.0  0.0278  0.0046   
791  0.0000  0.0013   0.0  0.0000  0.0000  0.0021   0.0  0.0000  0.0021   
792  0.0009  0.0004   0.0  0.0000  0.0192  0.0159   0.0  0.0128  0.0159   

       9     ...    1472    1473    1474    1475    1476    1477    1478  \
0    0.0017  ...  0.0957  0.0365  0.0365  0.0779  0.0365  0.0215  0.0611   
1    0.0061  ...  0.1105  0.0834  0.0834  0.0855  0.0834  0.0275  1.0000   
2    0.0061  ...  0.1105  0.0834  0.0834  0.0855  0.0834  0.0275  1.0000   
3    0.0026  ...  0.0529  0.0384  0.0384  0.0424  0.0384  0.0282  0.0369   
4    0.0000  ...  0.1402  0.0763  0.0763  0.1018  0.0763  0.0292  1.0000   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
788  0.0016  ...  0.0978  0.0758  0.0758  0.0851  0.0758  0.0373  0.0967   
789  0.0000  ...  0.1089  0.0316  0.0316  0.0956  0.0316  0.0491  0.0762   
790  0.0000  ...  0.1288  0.0835  0.0835  0.1011  0.0835  0.0175  0.0885   
791  0.0017  ...  0.0967  0.0348  0.0348  0.0789  0.0348  0.0224  0.0584   
792  0.0005  ...  0.0996  0.0771  0.0771  0.0842  0.0771  0.0410  0.0948   

       1479    1480   1481  
0    0.0022  0.0661  0.000  
1    0.0119  0.0854  0.000  
2    0.0119  0.0854  0.000  
3    0.0120  0.0554  0.002  
4    0.0077  0.1003  0.000  
..      ...     ...    ...  
788  0.0155  0.0852  0.000  
789  0.0157  0.1003  0.000  
790  0.0051  0.0871  0.000  
791  0.0023  0.0636  0.000  
792  0.0197  0.0930  0.001  

[793 rows x 1482 columns]

In [6]:
sc.describe()

0           1           2           3           4           5     \
count  793.000000  793.000000  793.000000  793.000000  793.000000  793.000000   
mean     0.014496    0.011758    0.001530    0.013665    0.006955    0.018708   
std      0.104898    0.067128    0.035584    0.093039    0.063036    0.062413   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.005300   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.016300   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

             6           7           8           9     ...        1472  \
count  793.000000  793.000000  793.000000  793.000000  ...  793.000000   
mean     0.023129    0.005859    0.033506    0.002284  ...    0.143214   
std      0.149049    0.051599    0.145239    0.037097  ...    0.214091   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    0.041700   
50%      0.000000    0.000000    0.005300    0.000000  ...    0.092100   
75%      0.000000    0.000000    0.016300    0.000000  ...    0.136400   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

             1473        1474        1475        1476        1477        1478  \
count  793.000000  793.000000  793.000000  793.000000  793.000000  793.000000   
mean     0.072247    0.108942    0.091020    0.067100    0.055545    0.140586   
std      0.103905    0.212597    0.103062    0.074005    0.144319    0.241689   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.015200    0.015200    0.033300    0.015200    0.000000    0.039600   
50%      0.059600    0.059600    0.078400    0.059600    0.033300    0.080700   
75%      0.095200    0.097200    0.111800    0.095200    0.049800    0.116900   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

             1479        1480        1481  
count  793.000000  793.000000  793.000000  
mean     0.036275    0.136995    0.006564  
std      0.146198    0.222055    0.079311  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.040100    0.000000  
50%      0.006100    0.079300    0.000000  
75%      0.019700    0.118700    0.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 1482 columns]

## 1.阈值上界测试

In [7]:
flag=[[1]*num_dis for _ in range(num_drug)]
# 样本标记函数flag
def judge(flag,threshold1):
    countp=0
    counte=0
    countf=0
    for i in range(num_drug):
        for j in range(num_dis):
            if us[i][j]==1:  #正例
                flag[i][j]=3
                countp+=1
                continue
            if score[i][j]==0:  #随机样本
                flag[i][j]=0
                counte+=1
                continue
            if score[i][j]>=threshold1:  #伪负样本
                flag[i][j]=2
                countf+=1
                continue
    print("已知的正样本的数量为:",countp)
    print("伪负样本的数量为：",countf)
    print("强负样本的数量为：",num_drug*num_dis-countp-counte-countf)
    print("简单负样本的数量为：",counte)
    
    
    return flag


In [10]:
threshold1=0.35
judge(flag,threshold1)
print("当前阈值为:",threshold1)

已知的正样本的数量为: 11540
伪负样本的数量为： 1036
强负样本的数量为： 616191
简单负样本的数量为： 546459
当前阈值为: 0.35


In [11]:
threshold1=0.34
judge(flag,threshold1)
print("当前阈值为:",threshold1)

已知的正样本的数量为: 11540
伪负样本的数量为： 1136
强负样本的数量为： 616091
简单负样本的数量为： 546459
当前阈值为: 0.34


In [16]:
threshold1=0.335
judge(flag,threshold1)
print("当前阈值为:",threshold1)

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 616062
简单负样本的数量为： 546459
当前阈值为: 0.335


In [12]:
threshold1=0.33
judge(flag,threshold1)
print("当前阈值为:",threshold1)

已知的正样本的数量为: 11540
伪负样本的数量为： 1682
强负样本的数量为： 615545
简单负样本的数量为： 546459
当前阈值为: 0.33


In [13]:
threshold1=0.32
judge(flag,threshold1)
print("当前阈值为:",threshold1)

已知的正样本的数量为: 11540
伪负样本的数量为： 1797
强负样本的数量为： 615430
简单负样本的数量为： 546459
当前阈值为: 0.32


选定阈值上界为0.335

In [17]:
threshold1=0.335
judge(flag,threshold1)
print("当前阈值为:",threshold1)

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 616062
简单负样本的数量为： 546459
当前阈值为: 0.335


## 2.阈值下界测试

In [18]:
flag=[[1]*num_dis for _ in range(num_drug)]
def judge2(flag,threshold1,threshold2):
    countp=0
    counte=0
    countf=0
    for i in range(num_drug):
        for j in range(num_dis):
            if us[i][j]==1:
                flag[i][j]=3
                countp+=1
                continue
            if score[i][j]>=threshold1:
                flag[i][j]=2
                countf+=1
                continue
            if score[i][j]<=threshold2:
                flag[i][j]=0
                counte+=1
                continue            
    print("已知的正样本的数量为:",countp)
    print("伪负样本的数量为：",countf)
    print("强负样本的数量为：",num_drug*num_dis-countp-counte-countf)
    print("简单负样本的数量为：",counte)    
    return flag

In [29]:
threshold1,threshold2=0.335,0.12
flag = judge2(flag,threshold1,threshold2)
print("当前阈值为:[%.3f,%.3f]"%(threshold2,threshold1))

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 60705
简单负样本的数量为： 1101816
当前阈值为:[0.120,0.335]


In [30]:
threshold1,threshold2=0.335,0.121
flag = judge2(flag,threshold1,threshold2)
print("当前阈值为:[%.3f,%.3f]"%(threshold2,threshold1))

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 59576
简单负样本的数量为： 1102945
当前阈值为:[0.121,0.335]


In [31]:
threshold1,threshold2=0.335,0.122
flag = judge2(flag,threshold1,threshold2)
print("当前阈值为:[%.3f,%.3f]"%(threshold2,threshold1))

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 58224
简单负样本的数量为： 1104297
当前阈值为:[0.122,0.335]


In [32]:
threshold1,threshold2=0.335,0.123
flag = judge2(flag,threshold1,threshold2)
print("当前阈值为:[%.3f,%.3f]"%(threshold2,threshold1))

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 57079
简单负样本的数量为： 1105442
当前阈值为:[0.123,0.335]


## 3.基于选定的阈值范围[0.121,0.335]进行负采样

In [33]:
threshold1,threshold2=0.335,0.121
flag = judge2(flag,threshold1,threshold2)
print("当前阈值为:[%.3f,%.3f]"%(threshold2,threshold1))

已知的正样本的数量为: 11540
伪负样本的数量为： 1165
强负样本的数量为： 59576
简单负样本的数量为： 1102945
当前阈值为:[0.121,0.335]


In [34]:
a=[1,2,3,7,5,99,6]
np.random.seed(77)
np.random.choice(a, 5, replace=False).tolist()

[3, 99, 1, 2, 7]

In [35]:
from collections import defaultdict
def selectNS(flag):
    #hard negtaive samples, hard negative number
    hns=defaultdict(list)
    hnn=defaultdict(int)
    #easy negtaive samples, easy negative number
    ens=defaultdict(list)
    enn=defaultdict(int)
    #record:记录有多少个药物节点没有强负样本
    record=0
    np.random.seed(77)
    for i in range(num_drug):
        for j in range(num_dis):
            if flag[i][j]==1:
                hns[i].append(j)
            if flag[i][j]==0:
                ens[i].append(j)
        hnn[i]=len(hns[i])
        enn[i]=len(ens[i])
        #当前节点不存在强负样本，需从简单负样本集进行随机选取
        if hnn[i]==0:
            record+=1
            rns=np.random.choice(ens[i], hardnegatives, replace=False).tolist()
            #print(i,rns)
            hns[i]=rns
            hnn[i]=hardnegatives
            continue
        #当前节点的强负样本数量过多，对其进行随机筛选
        if hnn[i]>hardnegatives:
            rns=np.random.choice(hns[i], hardnegatives, replace=False).tolist()
            hns[i]=rns
            #print(i,rns)
            hnn[i]=hardnegatives
    print("采取当前阈值时，不存在强负样本的药物数量：",record)
    #print(hns)
    #print(hnn)
    return hnn,hns
hnn,hns=selectNS(flag)

采取当前阈值时，不存在强负样本的药物数量： 287


In [36]:
hns[1481][-1]

304

## 4.生成实验用的数据集

In [37]:
np.random.seed(2023)
# save_prefix = './preprocess_NSAP/'
num_drug = 1482
num_dis = 793
drug_dis = np.load('./raw/txt2npy/us_edges.npy')
train_val_test_idx = np.load('./raw/txt2npz/train_val_test_idx.npz')
train_idx = train_val_test_idx['train_idx']
val_idx = train_val_test_idx['val_idx']
test_idx = train_val_test_idx['test_idx']    

In [38]:
#将b由数组转换为4*1的矩阵
b=np.array([1,2,3,4])[:,np.newaxis]
a=np.array([0]*len(b))[:,np.newaxis]
# c=np.hstack((a,b))
# d=np.vstack((a,b))
np.concatenate((a,b),axis=1).tolist()

[[0, 1], [0, 2], [0, 3], [0, 4]]

In [39]:
neg_candidates = []
counter=0
for drug,dis_nslist in hns.items():
    for dis in dis_nslist:
        neg_candidates.append([drug,dis])
print(len(neg_candidates))

35258


In [40]:
a=np.array([1,2,3,4,5])
b=np.array([2,3])
diff=np.setdiff1d(a,b)  
print(diff)

[1 4 5]


In [41]:
neg_candidates=np.array(neg_candidates)
# 随机选择验证集和测试集
idx = np.random.choice(len(neg_candidates), len(val_idx) + len(test_idx), replace=False)
val_neg_candidates = neg_candidates[sorted(idx[:len(val_idx)])]
test_neg_candidates = neg_candidates[sorted(idx[len(val_idx):])]
print(idx)
print(len(idx))

[ 5841 16728 11563 ... 31100 31840 19980]
4616


In [42]:
a=np.arange(len(neg_candidates))
b=np.array(idx)
other_idx=np.setdiff1d(a,b) 
train_neg_candidates =neg_candidates[other_idx]
print(len(train_neg_candidates))
print(other_idx)
neg_candidates[29258]

30642
[    0     1     2 ... 35255 35256 35257]


array([1270,  408])

In [43]:
save_prefix = './'
np.savez(save_prefix + 'dd_ns_train_val_test_pos_drug_dis.npz',
         train_pos_drug_dis=drug_dis[train_idx],
         val_pos_drug_dis=drug_dis[val_idx],
         test_pos_drug_dis=drug_dis[test_idx])
np.savez(save_prefix + 'dd_ns_train_val_test_neg_drug_dis.npz',
         train_neg_drug_dis=train_neg_candidates,
         val_neg_drug_dis=val_neg_candidates,
         test_neg_drug_dis=test_neg_candidates)

# metapath2vec label生成 

In [44]:
test_neg_candidates 

array([[   1,  279],
       [   2,  598],
       [   2,   38],
       ...,
       [1480,  204],
       [1480,  203],
       [1481,   65]])

In [45]:
list=[]
for uid,sid in test_neg_candidates:
    list.append(['u'+str(uid),'s'+str(sid),0])
list

[['u1', 's279', 0],
 ['u2', 's598', 0],
 ['u2', 's38', 0],
 ['u5', 's137', 0],
 ['u6', 's692', 0],
 ['u6', 's73', 0],
 ['u6', 's510', 0],
 ['u6', 's129', 0],
 ['u6', 's757', 0],
 ['u11', 's237', 0],
 ['u13', 's29', 0],
 ['u13', 's522', 0],
 ['u13', 's136', 0],
 ['u13', 's130', 0],
 ['u15', 's630', 0],
 ['u17', 's430', 0],
 ['u17', 's358', 0],
 ['u17', 's704', 0],
 ['u17', 's498', 0],
 ['u17', 's355', 0],
 ['u18', 's734', 0],
 ['u19', 's378', 0],
 ['u19', 's347', 0],
 ['u19', 's693', 0],
 ['u20', 's321', 0],
 ['u20', 's663', 0],
 ['u25', 's251', 0],
 ['u25', 's150', 0],
 ['u26', 's751', 0],
 ['u26', 's520', 0],
 ['u26', 's73', 0],
 ['u28', 's35', 0],
 ['u28', 's785', 0],
 ['u29', 's261', 0],
 ['u29', 's754', 0],
 ['u29', 's259', 0],
 ['u31', 's530', 0],
 ['u32', 's268', 0],
 ['u32', 's36', 0],
 ['u33', 's639', 0],
 ['u33', 's680', 0],
 ['u34', 's120', 0],
 ['u35', 's610', 0],
 ['u35', 's718', 0],
 ['u36', 's159', 0],
 ['u36', 's593', 0],
 ['u36', 's303', 0],
 ['u36', 's550', 0],
 ['u40'

In [46]:
test=pd.DataFrame(data=list)
test.to_csv('dd_label.csv',encoding='gbk')